/**
 * Automation ROI Analyzer
 * Analyzes ROI of automation systems
 */

const fs = require('fs');
const path = require('path');

class AutomationROIAnalyzer {
  constructor() {
    this.automationCosts = [];
    this.automationBenefits = [];
    this.roiData = [];
    
    this.dataPath = path.resolve(__dirname, 'automation-roi.json');
    this.benefitsPath = path.resolve(__dirname, 'automation-benefits.json');
    this.loadROIData();
  }

  // Track automation cost
  async trackAutomationCost(system, cost, type, metadata = {}) {
    console.log(`💰 Tracking automation cost: ${system} - $${cost}`);
    
    const automationCost = {
      id: this.generateAutomationCostId(),
      system,
      cost: parseFloat(cost),
      type, // 'development', 'maintenance', 'infrastructure', 'personnel'
      metadata,
      timestamp: new Date().toISOString(),
      month: new Date().toISOString().substring(0, 7)
    };
    
    this.automationCosts.push(automationCost);
    this.saveROIData();
    
    return automationCost;
  }

  // Track automation benefit
  async trackAutomationBenefit(system, benefit, type, metadata = {}) {
    console.log(`📈 Tracking automation benefit: ${system} - ${benefit}`);
    
    const automationBenefit = {
      id: this.generateBenefitId(),
      system,
      benefit: parseFloat(benefit),
      type, // 'time-saved', 'revenue-generated', 'cost-saved', 'efficiency-gain'
      metadata,
      timestamp: new Date().toISOString(),
      month: new Date().toISOString().substring(0, 7)
    };
    
    this.automationBenefits.push(automationBenefit);
    this.saveROIData();
    
    return automationBenefit;
  }

  // Calculate ROI for system
  calculateSystemROI(system, months = 12) {
    const systemCosts = this.automationCosts.filter(c => c.system === system);
    const systemBenefits = this.automationBenefits.filter(b => b.system === system);
    
    const totalCost = systemCosts.reduce((sum, c) => sum + c.cost, 0);
    const totalBenefit = systemBenefits.reduce((sum, b) => sum + b.benefit, 0);
    
    const roi = totalCost > 0 ? ((totalBenefit - totalCost) / totalCost * 100) : 0;
    
    const paybackPeriod = totalBenefit > 0 ? (totalCost / (totalBenefit / months)) : 0;
    
    return {
      system,
      totalCost: totalCost.toFixed(2),
      totalBenefit: totalBenefit.toFixed(2),
      roi: roi.toFixed(2),
      paybackPeriod: paybackPeriod.toFixed(1),
      months,
      netBenefit: (totalBenefit - totalCost).toFixed(2)
    };
  }

  // Calculate ROI for all systems
  calculateAllSystemsROI(months = 12) {
    const systems = [...new Set([...this.automationCosts, ...this.automationBenefits].map(item => item.system))];
    
    return systems.map(system => this.calculateSystemROI(system, months));
  }

  // Calculate time saved
  calculateTimeSaved(system, months = 12) {
    const timeBenefits = this.automationBenefits.filter(b => 
      b.system === system && b.type === 'time-saved'
    );
    
    const totalTimeSaved = timeBenefits.reduce((sum, b) => sum + b.benefit, 0);
    
    return {
      system,
      totalTimeSaved: totalTimeSaved.toFixed(2),
      hoursPerMonth: (totalTimeSaved / months).toFixed(2),
      hoursPerYear: (totalTimeSaved / months * 12).toFixed(2)
    };
  }

  // Calculate revenue generated by automation
  calculateAutomationRevenue(system, months = 12) {
    const revenueBenefits = this.automationBenefits.filter(b => 
      b.system === system && b.type === 'revenue-generated'
    );
    
    const totalRevenue = revenueBenefits.reduce((sum, b) => sum + b.benefit, 0);
    
    return {
      system,
      totalRevenue: totalRevenue.toFixed(2),
      revenuePerMonth: (totalRevenue / months).toFixed(2),
      revenuePerYear: (totalRevenue / months * 12).toFixed(2)
    };
  }

  // Calculate cost saved by automation
  calculateCostSaved(system, months = 12) {
    const costBenefits = this.automationBenefits.filter(b => 
      b.system === system && b.type === 'cost-saved'
    );
    
    const totalCostSaved = costBenefits.reduce((sum, b) => sum + b.benefit, 0);
    
    return {
      system,
      totalCostSaved: totalCostSaved.toFixed(2),
      costSavedPerMonth: (totalCostSaved / months).toFixed(2),
      costSavedPerYear: (totalCostSaved / months * 12).toFixed(2)
    };
  }

  // Calculate efficiency gain
  calculateEfficiencyGain(system, months = 12) {
    const efficiencyBenefits = this.automationBenefits.filter(b => 
      b.system === system && b.type === 'efficiency-gain'
    );
    
    const totalEfficiencyGain = efficiencyBenefits.reduce((sum, b) => sum + b.benefit, 0);
    
    return {
      system,
      totalEfficiencyGain: totalEfficiencyGain.toFixed(2),
      efficiencyGainPerMonth: (totalEfficiencyGain / months).toFixed(2)
    };
  }

  // Generate automation ROI report
  generateAutomationROIReport() {
    const allSystemsROI = this.calculateAllSystemsROI(12);
    
    const totalCost = allSystemsROI.reduce((sum, s) => sum + parseFloat(s.totalCost), 0);
    const totalBenefit = allSystemsROI.reduce((sum, s) => sum + parseFloat(s.totalBenefit), 0);
    const overallROI = totalCost > 0 ? ((totalBenefit - totalCost) / totalCost * 100) : 0;
    
    const timeSaved = allSystemsROI.map(s => this.calculateTimeSaved(s.system, 12));
    const totalTimeSaved = timeSaved.reduce((sum, s) => sum + parseFloat(s.totalTimeSaved), 0);
    
    const automationRevenue = allSystemsROI.map(s => this.calculateAutomationRevenue(s.system, 12));
    const totalAutomationRevenue = automationRevenue.reduce((sum, s) => sum + parseFloat(s.totalRevenue), 0);
    
    const costSaved = allSystemsROI.map(s => this.calculateCostSaved(s.system, 12));
    const totalCostSaved = costSaved.reduce((sum, s) => sum + parseFloat(s.totalCostSaved), 0);
    
    return {
      overall: {
        totalCost: totalCost.toFixed(2),
        totalBenefit: totalBenefit.toFixed(2),
        roi: overallROI.toFixed(2),
        netBenefit: (totalBenefit - totalCost).toFixed(2)
      },
      systems: allSystemsROI,
      timeSaved: {
        totalHours: totalTimeSaved.toFixed(2),
        bySystem: timeSaved
      },
      revenue: {
        total: totalAutomationRevenue.toFixed(2),
        bySystem: automationRevenue
      },
      costSavings: {
        total: totalCostSaved.toFixed(2),
        bySystem: costSaved
      }
    };
  }

  // Get ROI summary
  getROISummary() {
    const report = this.generateAutomationROIReport();
    
    return {
      overallROI: report.overall.roi,
      totalCost: report.overall.totalCost,
      totalBenefit: report.overall.totalBenefit,
      totalSystems: report.systems.length,
      totalTimeSaved: report.timeSaved.totalHours,
      totalAutomationRevenue: report.revenue.total,
      totalCostSaved: report.costSavings.total
    };
  }

  // Generate automation cost ID
  generateAutomationCostId() {
    return `auto-cost-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  }

  // Generate benefit ID
  generateBenefitId() {
    return `auto-benefit-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  }

  // Load ROI data
  loadROIData() {
    if (fs.existsSync(this.dataPath)) {
      const data = fs.readFileSync(this.dataPath, 'utf8');
      this.automationCosts = JSON.parse(data);
    }
    
    if (fs.existsSync(this.benefitsPath)) {
      const data = fs.readFileSync(this.benefitsPath, 'utf8');
      this.automationBenefits = JSON.parse(data);
    }
  }

  // Save ROI data
  saveROIData() {
    if (this.automationCosts.length > 1000) {
      this.automationCosts = this.automationCosts.slice(-1000);
    }
    if (this.automationBenefits.length > 1000) {
      this.automationBenefits = this.automationBenefits.slice(-1000);
    }
    
    fs.writeFileSync(this.dataPath, JSON.stringify(this.automationCosts, null, 2));
    fs.writeFileSync(this.benefitsPath, JSON.stringify(this.automationBenefits, null, 2));
  }
}

// CLI Interface
async function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  const analyzer = new AutomationROIAnalyzer();

  switch (command) {
    case 'track-cost':
      if (args[1] && args[2] && args[3]) {
        const cost = await analyzer.trackAutomationCost(args[1], args[2], args[3]);
        console.log('💰 Tracked Automation Cost:');
        console.log(JSON.stringify(cost, null, 2));
      } else {
        console.error('Usage: node automation-roi.js track-cost <system> <cost> <type>');
      }
      break;

    case 'track-benefit':
      if (args[1] && args[2] && args[3]) {
        const benefit = await analyzer.trackAutomationBenefit(args[1], args[2], args[3]);
        console.log('📈 Tracked Automation Benefit:');
        console.log(JSON.stringify(benefit, null, 2));
      } else {
        console.error('Usage: node automation-roi.js track-benefit <system> <benefit> <type>');
      }
      break;

    case 'roi':
      if (args[1]) {
        const roi = analyzer.calculateSystemROI(args[1]);
        console.log('📊 System ROI:');
        console.log(JSON.stringify(roi, null, 2));
      } else {
        const allROI = analyzer.calculateAllSystemsROI();
        console.log('📊 All Systems ROI:');
        console.log(JSON.stringify(allROI, null, 2));
      }
      break;

    case 'report':
      const report = analyzer.generateAutomationROIReport();
      console.log('📊 Automation ROI Report:');
      console.log(JSON.stringify(report, null, 2));
      break;

    case 'summary':
      const summary = analyzer.getROISummary();
      console.log('📊 ROI Summary:');
      console.log(JSON.stringify(summary, null, 2));
      break;

    default:
      console.log('📊 Automation ROI Analyzer');
      console.log('');
      console.log('Commands:');
      console.log('  track-cost    - Track automation cost');
      console.log('  track-benefit - Track automation benefit');
      console.log('  roi           - Calculate ROI');
      console.log('  report        - Generate ROI report');
      console.log('  summary       - Get ROI summary');
      console.log('');
      console.log('Examples:');
      console.log('  node automation-roi.js track-cost "support" 500 development');
      console.log('  node automation-roi.js track-benefit "support" 2000 time-saved');
      console.log('  node automation-roi.js roi');
      console.log('  node automation-roi.js roi support');
      console.log('  node automation-roi.js report');
      console.log('  node automation-roi.js summary');
  }
}

if (require.main === module) {
  main().catch(console.error);
}

module.exports = {
  AutomationROIAnalyzer
};
