/**
 * API client templates
 */

export const typescriptApiClientTemplate = `/**
 * {{name}} API Client
 * Generated by Aether Codegen
 */

interface {{name}}Response {
  // Define response types
}

interface {{name}}Error {
  message: string;
  status?: number;
}

export class {{name}}Client {
  private baseUrl: string;
  private authToken?: string;

  constructor(baseUrl: string = '{{baseUrl}}') {
    this.baseUrl = baseUrl;
  }

  {{#if hasAuth}}
  setAuthToken(token: string) {
    this.authToken = token;
  }

  clearAuthToken() {
    this.authToken = undefined;
  }

  private getAuthHeaders(): Record<string, string> {
    {{#if (eq authType 'bearer')}}
    return this.authToken ? { Authorization: \`Bearer \${this.authToken}\` } : {};
    {{else if (eq authType 'basic')}}
    return this.authToken ? { Authorization: \`Basic \${this.authToken}\` } : {};
    {{else if (eq authType 'api-key')}}
    return this.authToken ? { 'X-API-Key': this.authToken } : {};
    {{else}}
    return {};
    {{/if}}
  }
  {{/if}}

  private async request<T>(
    endpoint: string,
    options: RequestInit = {}
  ): Promise<T> {
    const url = \`\${this.baseUrl}\${endpoint}\`;

    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      {{#if hasAuth}}
      ...this.getAuthHeaders(),
      {{/if}}
      ...options.headers,
    };

    {{#if hasRetry}}
    let lastError: Error;
    for (let i = 0; i < 3; i++) {
      try {
        const response = await fetch(url, { ...options, headers });
        if (!response.ok) {
          throw new Error(\`HTTP error! status: \${response.status}\`);
        }
        return response.json();
      } catch (error) {
        lastError = error as Error;
        await new Promise(resolve => setTimeout(resolve, 1000 * (i + 1)));
      }
    }
    throw lastError;
    {{else}}
    const response = await fetch(url, { ...options, headers });

    {{#if hasErrorHandling}}
    if (!response.ok) {
      const error: {{name}}Error = await response.json();
      throw new Error(error.message || 'Request failed');
    }
    {{/if}}

    return response.json();
    {{/if}}
  }

  {{#each endpoints}}
  async {{camelCase name}}({{#if requestBody}}data: any{{/if}}): Promise<{{responseType}}> {
    return this.request<{{responseType}}>('/{{path}}', {
      method: '{{method}}',
      {{#if requestBody}}
      body: JSON.stringify(data),
      {{/if}}
    });
  }

  {{/each}}
}

export const {{camelCase name}}Client = new {{name}}Client();
`;

export const javascriptApiClientTemplate = `/**
 * {{name}} API Client
 * Generated by Aether Codegen
 */

export class {{name}}Client {
  constructor(baseUrl = '{{baseUrl}}') {
    this.baseUrl = baseUrl;
    this.authToken = null;
  }

  {{#if hasAuth}}
  setAuthToken(token) {
    this.authToken = token;
  }

  clearAuthToken() {
    this.authToken = null;
  }

  getAuthHeaders() {
    {{#if (eq authType 'bearer')}}
    return this.authToken ? { Authorization: \`Bearer \${this.authToken}\` } : {};
    {{else if (eq authType 'basic')}}
    return this.authToken ? { Authorization: \`Basic \${this.authToken}\` } : {};
    {{else if (eq authType 'api-key')}}
    return this.authToken ? { 'X-API-Key': this.authToken } : {};
    {{else}}
    return {};
    {{/if}}
  }
  {{/if}}

  async request(endpoint, options = {}) {
    const url = \`\${this.baseUrl}\${endpoint}\`;

    const headers = {
      'Content-Type': 'application/json',
      {{#if hasAuth}}
      ...this.getAuthHeaders(),
      {{/if}}
      ...options.headers,
    };

    {{#if hasRetry}}
    let lastError;
    for (let i = 0; i < 3; i++) {
      try {
        const response = await fetch(url, { ...options, headers });
        if (!response.ok) {
          throw new Error(\`HTTP error! status: \${response.status}\`);
        }
        return response.json();
      } catch (error) {
        lastError = error;
        await new Promise(resolve => setTimeout(resolve, 1000 * (i + 1)));
      }
    }
    throw lastError;
    {{else}}
    const response = await fetch(url, { ...options, headers });

    {{#if hasErrorHandling}}
    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.message || 'Request failed');
    }
    {{/if}}

    return response.json();
    {{/if}}
  }

  {{#each endpoints}}
  async {{camelCase name}}({{#if requestBody}}data{{/if}}) {
    return this.request('/{{path}}', {
      method: '{{method}}',
      {{#if requestBody}}
      body: JSON.stringify(data),
      {{/if}}
    });
  }

  {{/each}}
}

export const {{camelCase name}}Client = new {{name}}Client();
`;
