/**
 * Component templates
 */

export const reactComponentTemplate = `import React from 'react';

{{#if props}}
interface {{name}}Props {
  {{#each props}}
  {{name}}{{#unless required}}?{{/unless}}: {{type}};
  {{/each}}
}
{{/if}}

export const {{name}}: React.FC<{{#if props}}{{name}}Props{{else}}{}{{/if}}> = ({{#if props}}{ {{#each props}}{{name}}{{#unless required}}?{{/unless}}, {{/each}} }{{/if}}) => {
  {{#if hasState}}
  const [state, setState] = React.useState({});

  {{/if}}
  {{#each hooks}}
  const {{this}} = {{this}}();
  {{/each}}

  return (
    <div className="{{camelCase name}}">
      {/* Component content */}
    </div>
  );
};

export default {{name}};
`;

export const vueComponentTemplate = `<template>
  <div class="{{camelCase name}}">
    <!-- Component content -->
  </div>
</template>

<script setup lang="{{#if (eq language 'typescript')}}ts{{else}}js{{/if}}">
{{#if props}}
interface Props {
  {{#each props}}
  {{name}}{{#unless required}}?{{/unless}}: {{type}};
  {{/each}}
}

const props = defineProps<Props>();
{{/if}}

{{#if hasState}}
import { ref } from 'vue';
const state = ref({});
{{/if}}

{{#each hooks}}
// {{this}} hook
{{/each}}
</script>

<style scoped>
.{{camelCase name}} {
  /* Styles */
}
</style>
`;

export const svelteComponentTemplate = `<script lang="{{#if (eq language 'typescript')}}ts{{else}}js{{/if}}">
{{#if props}}
export let {{#each props}}{{name}}{{#unless required}} = undefined{{/unless}}{{#unless @last}}, {{/unless}}{{/each}};
{{/if}}

{{#if hasState}}
let state = {};
{{/if}}
</script>

<div class="{{camelCase name}}">
  <!-- Component content -->
</div>

<style>
.{{camelCase name}} {
  /* Styles */
}
</style>
`;

export const solidComponentTemplate = `import { createSignal } from 'solid-js';

{{#if props}}
interface {{name}}Props {
  {{#each props}}
  {{name}}{{#unless required}}?{{/unless}}: {{type}};
  {{/each}}
}
{{/if}}

export function {{name}}({{#if props}}{ {{#each props}}{{name}}{{#unless required}}?{{/unless}}, {{/each}} }{{/if}}: {{#if props}}{{name}}Props{{else}}{}{{/if}}) {
  {{#if hasState}}
  const [state, setState] = createSignal({});

  {{/if}}
  return (
    <div class="{{camelCase name}}">
      {/* Component content */}
    </div>
  );
}

export default {{name}};
`;

export const vanillaComponentTemplate = `/**
 * {{name}} Component
 * Generated by Aether Codegen
 */

export class {{name}} {
  constructor(options: any = {}) {
    this.options = options;
  }

  render() {
    return \`<div class="{{camelCase name}}">
      <!-- Component content -->
    </div>\`;
  }

  mount(element: HTMLElement) {
    element.innerHTML = this.render();
  }
}

export default {{name}};
`;
