name = "notion-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[routes]]
pattern = "notion.a-to-mind.com"
custom_domain = true

[[d1_databases]]
binding = "DB_RUNS"
database_name = "aether-bridge-db"
database_id = "f29243db-5b7a-407b-aa38-64091c1e0676"

[vars]
ENVIRONMENT = "production"
