import fs from 'fs-extra';
import path from 'path';
import { GenerateOptions, GenerateResult } from '../types.js';

/**
 * Generate a component
 */
export async function generateComponent(options: GenerateOptions): Promise<GenerateResult> {
  try {
    const outputPath = options.path || path.join(process.cwd(), 'src', 'components');
    await fs.ensureDir(outputPath);

    const fileName = `${options.name}.${options.language === 'typescript' ? 'tsx' : 'jsx'}`;
    const filePath = path.join(outputPath, fileName);

    const content = generateComponentContent(options);
    await fs.writeFile(filePath, content);

    return {
      success: true,
      data: {
        filesCreated: [fileName],
        outputPath,
      },
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to generate component',
    };
  }
}

/**
 * Generate an API client
 */
export async function generateApiClient(options: GenerateOptions): Promise<GenerateResult> {
  try {
    const outputPath = options.path || path.join(process.cwd(), 'src', 'api');
    await fs.ensureDir(outputPath);

    const fileName = `${options.name}Client.${options.language}`;
    const filePath = path.join(outputPath, fileName);

    const content = generateApiClientContent(options);
    await fs.writeFile(filePath, content);

    return {
      success: true,
      data: {
        filesCreated: [fileName],
        outputPath,
      },
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to generate API client',
    };
  }
}

/**
 * Generate a schema
 */
export async function generateSchema(options: GenerateOptions): Promise<GenerateResult> {
  try {
    const outputPath = options.path || path.join(process.cwd(), 'src', 'schemas');
    await fs.ensureDir(outputPath);

    const fileName = `${options.name}Schema.${options.language}`;
    const filePath = path.join(outputPath, fileName);

    const content = generateSchemaContent(options);
    await fs.writeFile(filePath, content);

    return {
      success: true,
      data: {
        filesCreated: [fileName],
        outputPath,
      },
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to generate schema',
    };
  }
}

/**
 * Generate a type
 */
export async function generateType(options: GenerateOptions): Promise<GenerateResult> {
  try {
    const outputPath = options.path || path.join(process.cwd(), 'src', 'types');
    await fs.ensureDir(outputPath);

    const fileName = `${options.name}.${options.language}`;
    const filePath = path.join(outputPath, fileName);

    const content = generateTypeContent(options);
    await fs.writeFile(filePath, content);

    return {
      success: true,
      data: {
        filesCreated: [fileName],
        outputPath,
      },
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to generate type',
    };
  }
}

/**
 * Generate boilerplate
 */
export async function generateBoilerplate(options: GenerateOptions): Promise<GenerateResult> {
  try {
    const outputPath = options.path || path.join(process.cwd(), 'src', 'boilerplate');
    await fs.ensureDir(outputPath);

    const fileName = `${options.name}.${options.language}`;
    const filePath = path.join(outputPath, fileName);

    const content = generateBoilerplateContent(options);
    await fs.writeFile(filePath, content);

    return {
      success: true,
      data: {
        filesCreated: [fileName],
        outputPath,
      },
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to generate boilerplate',
    };
  }
}

function generateComponentContent(options: GenerateOptions): string {
  const isTS = options.language === 'typescript';
  const ext = isTS ? 'tsx' : 'jsx';

  if (options.framework === 'react') {
    return `import React from 'react';

interface ${options.name}Props {
  // Add your props here
}

export const ${options.name}: React.FC<${options.name}Props> = (props) => {
  return (
    <div className="${options.name.toLowerCase()}">
      {/* Component content */}
    </div>
  );
};

export default ${options.name};
`;
  }

  return `// ${options.name} component
// Generated by Aether CLI

export class ${options.name} {
  constructor() {
    // Initialize
  }

  render() {
    return '<div></div>';
  }
}
`;
}

function generateApiClientContent(options: GenerateOptions): string {
  const isTS = options.language === 'typescript';

  if (isTS) {
    return `/**
 * ${options.name} API Client
 * Generated by Aether CLI
 */

interface ${options.name}Response {
  // Define response types
}

export class ${options.name}Client {
  private baseUrl: string;

  constructor(baseUrl: string = '/api/${options.name.toLowerCase()}') {
    this.baseUrl = baseUrl;
  }

  async get(): Promise<${options.name}Response> {
    const response = await fetch(this.baseUrl);
    return response.json();
  }

  async post(data: any): Promise<${options.name}Response> {
    const response = await fetch(this.baseUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });
    return response.json();
  }
}

export const ${options.name.toLowerCase()}Client = new ${options.name}Client();
`;
  }

  return `/**
 * ${options.name} API Client
 * Generated by Aether CLI
 */

export class ${options.name}Client {
  constructor(baseUrl = '/api/${options.name.toLowerCase()}') {
    this.baseUrl = baseUrl;
  }

  async get() {
    const response = await fetch(this.baseUrl);
    return response.json();
  }

  async post(data) {
    const response = await fetch(this.baseUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });
    return response.json();
  }
}

export const ${options.name.toLowerCase()}Client = new ${options.name}Client();
`;
}

function generateSchemaContent(options: GenerateOptions): string {
  const isTS = options.language === 'typescript';

  if (isTS) {
    return `/**
 * ${options.name} Schema
 * Generated by Aether CLI
 */

import { z } from 'zod';

export const ${options.name}Schema = z.object({
  // Define your schema fields here
  id: z.string(),
  name: z.string(),
  createdAt: z.date().optional(),
});

export type ${options.name} = z.infer<typeof ${options.name}Schema>;
`;
  }

  return `/**
 * ${options.name} Schema
 * Generated by Aether CLI
 */

export const ${options.name}Schema = {
  // Define your schema validation here
  validate: (data) => {
    // Add validation logic
    return true;
  },
};
`;
}

function generateTypeContent(options: GenerateOptions): string {
  const isTS = options.language === 'typescript';

  if (isTS) {
    return `/**
 * ${options.name} Type
 * Generated by Aether CLI
 */

export interface ${options.name} {
  id: string;
  name: string;
  // Add your properties here
}

export type ${options.name}Create = Omit<${options.name}, 'id'>;
export type ${options.name}Update = Partial<${options.name}Create>;
`;
  }

  return `/**
 * ${options.name} Type
 * Generated by Aether CLI
 */

export class ${options.name} {
  constructor(data) {
    this.id = data.id;
    this.name = data.name;
    // Add your properties here
  }
}
`;
}

function generateBoilerplateContent(options: GenerateOptions): string {
  const isTS = options.language === 'typescript';

  if (isTS) {
    return `/**
 * ${options.name} Boilerplate
 * Generated by Aether CLI
 */

export class ${options.name} {
  private state: any;

  constructor(initialState?: any) {
    this.state = initialState || {};
  }

  // Add your methods here

  getState() {
    return this.state;
  }

  setState(newState: any) {
    this.state = { ...this.state, ...newState };
  }
}

export default ${options.name};
`;
  }

  return `/**
 * ${options.name} Boilerplate
 * Generated by Aether CLI
 */

export class ${options.name} {
  constructor(initialState) {
    this.state = initialState || {};
  }

  // Add your methods here

  getState() {
    return this.state;
  }

  setState(newState) {
    this.state = { ...this.state, ...newState };
  }
}

export default ${options.name};
`;
}
