# Pre-Commit Hooks Skill
# Automatically runs compliance checks before commits

param(
    [switch]$Install,
    [switch]$Run,
    [string]$Skip = ""
)

$ErrorActionPreference = "Stop"

Write-Host "=== PRE-COMMIT HOOKS ===" -ForegroundColor Cyan

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = "C:\Users\adamm\Aether"

# Define checks
$checks = @(
    @{ Name = "Frontend-Backend Sync"; Script = "$scriptDir\frontend-sync\skill.ps1"; Critical = $true },
    @{ Name = "Frontend-Sync Guard"; Script = "$scriptDir\frontend-sync-guard\skill.ps1"; Critical = $true },
    @{ Name = "Real vs Simulated Data"; Script = "$scriptDir\real-vs-simulated\skill.ps1 -Audit"; Critical = $true }
)

# Install hooks
if ($Install) {
    Write-Host "Installing pre-commit hooks..." -ForegroundColor Yellow
    
    $hookContent = @"
#!/usr/bin/env pwsh
# Pre-commit hook - Auto-generated by pre-commit-hooks skill

& "$scriptDir\skill.ps1" -Run
if (`$LASTEXITCODE -ne 0) {
    Write-Host "❌ Pre-commit checks failed. Commit blocked." -ForegroundColor Red
    exit 1
}
"@
    
    $hookPath = "$repoRoot\.git\hooks\pre-commit"
    $hookContent | Out-File -FilePath $hookPath -Encoding utf8 -Force
    
    # Make executable on Unix
    if ($IsLinux -or $IsMacOS) {
        chmod +x $hookPath
    }
    
    Write-Host "✅ Pre-commit hooks installed" -ForegroundColor Green
    exit 0
}

# Run checks
if ($Run) {
    Write-Host "Running pre-commit checks..." -ForegroundColor Yellow
    Write-Host ""
    
    $failedChecks = @()
    $warningChecks = @()
    $skippedChecks = $Skip -split ','
    
    foreach ($check in $checks) {
        if ($skippedChecks -contains $check.Name) {
            Write-Host "⏭️  Skipping: $($check.Name)" -ForegroundColor Yellow
            continue
        }
        
        Write-Host "Running: $($check.Name)..." -ForegroundColor Cyan
        
        try {
            & $check.Script -AutoFix
            $exitCode = $LASTEXITCODE
            
            if ($exitCode -eq 0) {
                Write-Host "✅ PASSED: $($check.Name)" -ForegroundColor Green
            } elseif ($exitCode -eq 2) {
                Write-Host "⚠️  WARNING: $($check.Name)" -ForegroundColor Yellow
                $warningChecks += $check.Name
            } else {
                Write-Host "❌ FAILED: $($check.Name)" -ForegroundColor Red
                $failedChecks += $check.Name
            }
        } catch {
            Write-Host "❌ ERROR: $($check.Name) - $($_.Exception.Message)" -ForegroundColor Red
            $failedChecks += $check.Name
        }
        
        Write-Host ""
    }
    
    # Summary
    Write-Host "=== PRE-COMMIT SUMMARY ===" -ForegroundColor Cyan
    
    if ($failedChecks.Count -gt 0) {
        Write-Host "❌ Failed checks: $($failedChecks.Count)" -ForegroundColor Red
        foreach ($check in $failedChecks) {
            Write-Host "  - $check" -ForegroundColor Red
        }
        Write-Host ""
        Write-Host "Commit blocked. Fix the issues or skip with -Skip." -ForegroundColor Red
        exit 1
    }
    
    if ($warningChecks.Count -gt 0) {
        Write-Host "⚠️  Warnings: $($warningChecks.Count)" -ForegroundColor Yellow
        foreach ($check in $warningChecks) {
            Write-Host "  - $check" -ForegroundColor Yellow
        }
        Write-Host ""
        Write-Host "Commit allowed with warnings." -ForegroundColor Yellow
    }
    
    Write-Host "✅ All critical checks passed. Commit allowed." -ForegroundColor Green
    exit 0
}

Write-Host "Usage: .\skill.ps1 -Install | -Run" -ForegroundColor Yellow
exit 1